# Generated by Django 4.0.3 on 2022-03-25 17:42

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_funcionario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(default=1, upload_to='media/foto_perfil'),
            preserve_default=False,
        ),
    ]
