# Generated by Django 4.0.3 on 2022-03-28 19:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, upload_to='foto_perfil'),
        ),
    ]
