# Generated by Django 4.0.3 on 2022-03-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_documeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='documeto',
            new_name='documento',
        ),
    ]
